
path: D:\SEGi Kota Damansara\Semesters\Year 3\Y3 Sem 1\Final Year Project 1\YOLOv8 Weapon Recognition System\Weapon Dataset # dataset root dir
train: train  # train images (relative to 'path')
val: train  # val images (relative to 'path')

# Classes
names:
  0: HandGun
  1: Knife
  2: Rifle